version: '3.8'

services:
  mongodb-dev:
    image: mongo:7.0
    restart: unless-stopped
    container_name: gai-db-dev
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    volumes:
      - "dev_mongo_data:/data/db"
      - "dev_mongo_conf:/data/configdb"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      gai-dev:

  server-dev:
    build:
      context: ./server
      target: development
    restart: unless-stopped
    container_name: gai-server-dev
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb-dev
    env_file:
      - ./server/.env.development
    command: ["npm", "run", "start:dev"]
    networks:
      gai-dev:

  client-dev:
    build:
      context: ./client
      target: development
    restart: unless-stopped
    container_name: gai-client-dev
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env.development
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      gai-dev:
    depends_on:
      - server-dev


volumes:
  dev_mongo_data:
  dev_mongo_conf:

networks:
  gai-dev: