import { Student, studentColumns } from "@/components/allStudent/list/columns";
import { DataTable } from "@/components/common/table";

const AllStudentsPage: React.FC = () => {
  const data: Student[] = [
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
    {
      id: "1",
      name: "Billal",
      technology: "Billal",
      roll: 5656,
      registrationNo: 5656,
      session: "Billal",
      shift: "Billal",
      active: true,
    },
  ];

  return (
    <div>
      <div className="container mx-auto px-4 py-5">
        <h1 className="text-3xl font-bold text-foreground mb-4">Students</h1>
        <div className="bg-secondary p-6 rounded space-y-3 border">
          <h1 className="text-xl font-semibold text-foreground">
            All passed students.
          </h1>
          <DataTable<Student, any> columns={studentColumns} data={data} />
        </div>
      </div>
    </div>
  );
};
export default AllStudentsPage;
