export enum FormFieldType {
  INPUT = "INPUT",
  NUMBER = "NUMBER",
  EMAIL = "EMAIL",
  PASSWORD = "PASSWORD",
  FILE = "FILE",
  CHECKBOX = "CHECKBOX",
  BOOLSELECT = "BOOLSELECT",
  SELECT = "SELECT",
  TEXTAREA = "TEXTAREA",
  SKELETON = "SKELETON",
  UPLOAD = "UPLOAD",
  CHECKBOX_GROUP = "CHECKBOX_GROUP",
}
